<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PackageId>Majo.LineEditor</PackageId>
        <Version>0.0.2</Version>
        <Authors>Sweety Majo</Authors>
        <Description>A small, cross-platform interactive line editor for .NET.</Description>
        <PackageTags>terminal;console;line-editor;cli;linenoise</PackageTags>
        <PackageOutputPath>$(MSBuildProjectDirectory)/../artifacts/nuget</PackageOutputPath>
        
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/sweetymajo/Majo.LineEditor</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PackageProjectUrl>https://github.com/sweetymajo/Majo.LineEditor</PackageProjectUrl>
        
        <PackageReadmeFile>README.nuget.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="Wcwidth" Version="4.0.1" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="README.nuget.md" Pack="true" PackagePath="/" />
        <None Include="../LICENSE.txt" Pack="true" PackagePath="/" />
        
        <None Include="runtimes/linux-x64/native/libmajo_line_editor.so" Pack="true"
              PackagePath="runtimes/linux-x64/native/libmajo_line_editor.so" />
    </ItemGroup>

    <Target Name="ExposePosixLineEditorNative" 
            BeforeTargets="GetCopyToOutputDirectoryItems;GetCopyToPublishDirectoryItems">

        <ItemGroup>
            <ContentWithTargetPath Include="$(MSBuildProjectDirectory)/runtimes/linux-x64/native/libmajo_line_editor.so"
                                   TargetPath="libmajo_line_editor.so"
                                   CopyToOutputDirectory="PreserveNewest"
                                   CopyToPublishDirectory="PreserveNewest" />
        </ItemGroup>

    </Target>
</Project>
